### PR TITLE
Python 3.14, drop Python 3.10, upgrade to numpy 2.4.x, scipy 1.17, networkx 3.6, ipython 9.x for passagemath-10.8.x

### PR DESCRIPTION
**Pull request by mkoeppe**
https://repology.org/project/python/versions

Use `./configure --without-system-python3 --disable-notebook && make build` to test the build with Python 3.14.

- https://docs.scipy.org/doc/scipy/release/1.17.0-notes.html

### CODE REVIEW

**Comment by mkoeppe** [comment]
```
  [sagemath_objects-10.6.1.rc1]   [spkg-install] sage/cpython/atexit.c:1252:12: error: unknown type name 'atexit_py_callback'; did you mean 'atexit_callback'?
  [sagemath_objects-10.6.1.rc1]   [spkg-install]  1252 |     static atexit_callback ** _atexit_callbacks(PyObject *self) {
  [sagemath_objects-10.6.1.rc1]   [spkg-install]       |            ^~~~~~~~~~~~~~~
  [sagemath_objects-10.6.1.rc1]   [spkg-install]       |            atexit_callback
  [sagemath_objects-10.6.1.rc1]   [spkg-install] sage/cpython/atexit.c:1250:29: note: expanded from macro 'atexit_callback'
  [sagemath_objects-10.6.1.rc1]   [spkg-install]  1250 |     #define atexit_callback atexit_py_callback
  [sagemath_objects-10.6.1.rc1]   [spkg-install]       |                             ^
```

**Comment by user202729** [comment]
not sure if you're interested, but I analyzed the atexit issue in python3.14 at `https://github.com/sagemath/sage/issues/40890`

apart from that, cysignals may be broken too. `https://github.com/sagemath/cysignals/issues/232`
