### ISSUE TITLE
macos wheels: graphviz: Undefined symbols:  "_wind", referenced from: _vrml_bezier in gvrender_gd_vrml.o

### ISSUE THREAD

**Issue by mkoeppe** [passagemath/passagemath#2642]
```
  [graphviz-14.0.0]   [spkg-install] /bin/bash ../../libtool  --tag=CC   --mode=link gcc  -g -O2 -Wall -Wextra -Wmissing-include-dirs -Wswitch-default -Wfloat-equal -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wconversion -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -fno-common -Wall -version-info 8:0:0  -L/var/tmp/sage-local/lib -L/var/tmp/sage-local/lib -L/var/tmp/sage-local/lib -Wl,-ld_classic -Wl,-headerpad_max_install_names  -Wl,-headerpad_max_install_names -o libgvplugin_gd.la -rpath /var/tmp/sage-local/lib/graphviz gvplugin_gd.lo gvrender_gd.lo gvrender_gd_vrml.lo gvtextlayout_gd.lo gvloadimage_gd.lo gvdevice_gd.lo ../../lib/gvc/libgvc.la ../../lib/cgraph/libcgraph.la ../../lib/cdt/libcdt.la  -lgd -lgd -lm  
  [graphviz-14.0.0]   [spkg-install] libtool: link: gcc -dynamiclib  -o .libs/libgvplugin_gd.8.dylib  .libs/gvplugin_gd.o .libs/gvrender_gd.o .libs/gvrender_gd_vrml.o .libs/gvtextlayout_gd.o .libs/gvloadimage_gd.o .libs/gvdevice_gd.o   -L/var/tmp/sage-local/lib ../../lib/gvc/.libs/libgvc.dylib ../../lib/cgraph/.libs/libcgraph.dylib ../../lib/cdt/.libs/libcdt.dylib -lgd -lm  -g -O2 -Wl,-ld_classic -Wl,-headerpad_max_install_names -Wl,-headerpad_max_install_names -Wl,-dylib_file -Wl,/var/tmp/sage-local/lib/libxdot.4.dylib:/var/tmp/sage-local/var/tmp/sage/build/graphviz-14.0.0/src/lib/xdot/.libs/libxdot.dylib -Wl,-dylib_file -Wl,/var/tmp/sage-local/lib/libpathplan.4.dylib:/var/tmp/sage-local/var/tmp/sage/build/graphviz-14.0.0/src/lib/pathplan/.libs/libpathplan.dylib -Wl,-dylib_file -Wl,/var/tmp/sage-local/lib/libcgraph.8.dylib:/var/tmp/sage-local/var/tmp/sage/build/graphviz-14.0.0/src/lib/cgraph/.libs/libcgraph.dylib -Wl,-dylib_file -Wl,/var/tmp/sage-local/lib/libcdt.6.dylib:/var/tmp/sage-local/var/tmp/sage/build/graphviz-14.0.0/src/lib/cdt/.libs/libcdt.dylib -Wl,-dylib_file -Wl,/var/tmp/sage-local/lib/libcdt.6.dylib:/var/tmp/sage-local/var/tmp/sage/build/graphviz-14.0.0/src/lib/cdt/.libs/libcdt.dylib   -install_name  /var/tmp/sage-local/lib/graphviz/libgvplugin_gd.8.dylib -compatibility_version 9 -current_version 9.0 -Wl,-single_module
  [graphviz-14.0.0]   [spkg-install] ld: warning: -dylib_file is deprecated. Use -F or -L to control where indirect dylibs are found
  [graphviz-14.0.0]   [spkg-install] ld: warning: -ld_classic is deprecated and will be removed in a future release
  [graphviz-14.0.0]   [spkg-install] Undefined symbols for architecture x86_64:
  [graphviz-14.0.0]   [spkg-install]   "_wind", referenced from:
  [graphviz-14.0.0]   [spkg-install]       _vrml_bezier in gvrender_gd_vrml.o
  [graphviz-14.0.0]   [spkg-install] ld: symbol(s) not found for architecture x86_64
  [graphviz-14.0.0]   [spkg-install] clang: error: linker command failed with exit code 1 (use -v to see invocation)
  [graphviz-14.0.0]   [spkg-install] make[6]: *** [Makefile:683: libgvplugin_gd.la] Error 1
```

**Comment by mkoeppe** [comment]
Still after upgrade to 15.1.1

**Comment by mkoeppe** [comment]
Fixed by #2644
